"""Created a subscription table

Revision ID: 51206eb5f521
Revises: 3bf9ee92ba7e
Create Date: 2022-02-14 17:29:39.229835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51206eb5f521'
down_revision = '3bf9ee92ba7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcription')
    # ### end Alembic commands ###
